Home work №14: Exercise 7_47
2lucky1/It-Step-Home-Work pull request #3
Opened 2017-08-18 19:55 UTC by 2lucky1

The mass of each person from a certain group of people is known. People who have weight more than 100 kg we shall conditionally call fat (it is known that there is at least one such person in the group).
Determine the average mass of fat people and the average mass of other people.

2017-08-21 09:30 UTC, strazhkoe requested changes

2017-08-21 09:30 UTC, strazhkoe commented on src/com/muntian/ht14_Exercise_7_47/AverageWeight.java
> +    private static double[] group = {60, 100, 77, 82, 90, 120, 110};
Сделайте этот массив локальной переменной в методе main. Вы все равно передаете его во все методы (что есть правильно)

2017-08-21 09:30 UTC, strazhkoe commented on src/com/muntian/ht14_Exercise_7_47/AverageWeight.java
> +    private static double[] group = {60, 100, 77, 82, 90, 120, 110};
Можно ли остальные глобальные переменные (что объявлены выше) сделать локальными?

2017-08-21 14:38 UTC, 2lucky1 commented
Changes have been made according to your remarks. Check, please.

2017-08-23 13:12 UTC, strazhkoe commented
Please do not use smiles in commit messages 
![image](https://user-images.githubusercontent.com/1845841/29617504-cb261498-881d-11e7-9b8b-2c92020761b0.png)

2017-08-23 13:14 UTC, strazhkoe approved these changes

2017-08-23 13:14 UTC, merged