Ht15 exercise 3 34 chess
2lucky1/It-Step-Home-Work pull request #4
Opened 2017-08-27 20:21 UTC by 2lucky1

The chessboard field is defined by a pair of natural numbers, each of which does not exceed 8: the first number is the number of the vertical (when counting from left to right), the second is the horizontal number (with a bottom-up count). Given natural numbers a, b, c, d, each of which does not exceed 8.
a) On the field (a, b) is a rook. Write the condition under which it threatens the field (c, d).
b) On the field (a, b) there is an elephant. Write the condition under which it threatens the field (c, d).
c) On the field (a, b) is the king. Write down the condition under which it can go one step to the field (c, d).
d) In the field (a, b) is the queen. Write the condition under which it threatens the field (c, d).
e) There is a white pawn on the field (a, b). Write down the condition under which it can go one step to the field (c, d).
f) There is a black pawn in the field (a, b). Write the condition under which it can go one step to the field (c, d).
g) A horse is located on the field (a, b). Write the condition under which it threatens the field (c, d).

2017-09-02 19:23 UTC, strazhkoe requested changes
Good job! Please fix my minor comments

2017-09-02 19:23 UTC, strazhkoe commented on src/com/muntian/ht15_Exercise_3_34/Chess.java
> +        } else {
else is redundant

2017-09-02 19:23 UTC, strazhkoe commented on src/com/muntian/ht15_Exercise_3_34/Chess.java
> +                            System.out.println("You have chosen a rook");
You should move the phrase "You have chosen" to a constant.

2017-09-02 21:27 UTC, 2lucky1 commented
Task was fixed according to the comments

2017-10-08 10:35 UTC, strazhkoe approved these changes

2017-10-08 10:35 UTC, merged