Ht17 encapsulation in fractions
2lucky1/It-Step-Home-Work pull request #6
Opened 2017-09-04 08:29 UTC by 2lucky1

Add encapsulation in homework with a class of fractions . Hide fields, creat public get and set methods. Add Constructor(s)

2017-09-10 09:04 UTC, strazhkoe requested changes

2017-09-10 09:04 UTC, strazhkoe commented on src/com/muntian/ht17_Encapsulation/ActionsWithFractions.java
> +    private static void additionOfFractionalParts(Fractions firstSummand, Fractions secondSummand, Fractions result) {
Все арифметические операции необходимо перенести в класс Fraction и сделать их нестатическими

2017-09-10 20:22 UTC, 2lucky1 commented on src/com/muntian/ht17_Encapsulation/ActionsWithFractions.java
> +    private static void additionOfFractionalParts(Fractions firstSummand, Fractions secondSummand, Fractions result) {
Task was fixed according to the comments

2017-09-14 17:32 UTC, strazhkoe requested changes

2017-09-14 17:32 UTC, strazhkoe commented on src/com/muntian/ht20_Passport/Passport.java
> +public class Passport {
How did this class get here?

2017-09-14 17:32 UTC, strazhkoe commented on src/com/muntian/ht20_Passport/Visa.java
> +public class Visa {
How did this class get here?

2017-09-14 20:04 UTC, 2lucky1 commented on src/com/muntian/ht20_Passport/Visa.java
> +public class Visa {
My mistake.  Already fixed.

2017-09-17 08:24 UTC, strazhkoe approved these changes

2017-09-17 08:24 UTC, merged