Ht18 grant
2lucky1/It-Step-Home-Work pull request #7
Opened 2017-09-06 14:42 UTC by 2lucky1

To create a program for the accrual of scholarships to students on the results of the examination session. Information on the results of the session includes:
- last name;
- name;
- patronymic;
- group number;
- examination marks.
The number of examination marks is at least 3 and not more than 5. The scholarship is awarded to students who passed all the exams in the session, according to the following rules. Students who passed all the exams for "excellent" receive a mark-up equal to 100%; students who passed the exams for "good" and "excellent" - 50%; and students who passed exams for "good" - 25%. The scholarship is not awarded to students who have more than two satisfactory grades in the session.
List of students of each group that received a scholarship, display on the screen, ordering it alphabetically.

2017-09-10 09:43 UTC, strazhkoe requested changes

2017-09-10 09:43 UTC, strazhkoe commented on src/com/muntian/ht18_Grant/AccrualOfScholarships.java
> +                case 5:
Эти числа из кейсов нужно вынести в константы

2017-09-10 09:43 UTC, strazhkoe commented on src/com/muntian/ht18_Grant/Student.java
> +        return academicPerformance;
Тут должно происходить вычисление исходя из оценок

2017-09-10 09:43 UTC, strazhkoe commented on src/com/muntian/ht18_Grant/Student.java
> +    public void setAcademicPerformance(int academicPerformance) {
этого метода быть не должно

2017-09-10 23:11 UTC, 2lucky1 commented
Task was fixed according to the comments

2017-09-18 07:40 UTC, strazhkoe approved these changes

2017-09-18 07:41 UTC, merged